services:
  - type: web
    name: openai-proxy
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: OPENAI_API_KEY
        sync: true
      - key: YOUTUBE_API_KEY
        sync: true
      - key: GEMINI_API_KEY
        sync: true
      - key: DOWNSUB_API_KEY
        sync: true
